### ISSUE TITLE
`create_uda!` method is broken due to typo

### ISSUE THREAD

**Issue by maxcorbin** [dropofwill/rtasklib#3]
Looks like in `controller.rb`, you've got references to `update_config` under the `create_uda!` method:

```
def create_uda! name, type: "string", label: nil, values: nil,
               default: nil, urgency: nil
  label = name if label.nil?

  update_config("uda.#{name}.type",  type)
  update_config("uda.#{name}.label", label)
  update_config("uda.#{name}.values",  values)  unless values.nil?
  update_config("uda.#{name}.default", default) unless default.nil?
  update_config("uda.#{name}.urgency", urgency) unless urgency.nil?
end
```

There isn't any `update_config` method, so when you try to use the `create_uda!` method, you get this error:

`[...]controller.rb:372:in 'create_uda!': undefined method 'update_config' for #<Rtasklib::TaskWarrior:0x007fef1b483e80> (NoMethodError)`

Unless I'm misunderstanding, this should be an easy fix:

```
def create_uda! name, type: "string", label: nil, values: nil,
               default: nil, urgency: nil
  label = name if label.nil?

  update_config!("uda.#{name}.type",  type)
  update_config!("uda.#{name}.label", label)
  update_config!("uda.#{name}.values",  values)  unless values.nil?
  update_config!("uda.#{name}.default", default) unless default.nil?
  update_config!("uda.#{name}.urgency", urgency) unless urgency.nil?
end
```

Happy to submit a pull request if you prefer.

**Comment by dropofwill** [comment]
You're correct, looks like I broke that method with [this commit](https://github.com/dropofwill/rtasklib/commit/5d26750ab353f731ce9a915856e5488bba82159d#diff-32cf1ebc3d1df710e1a46d6b79a85cb8L19).

If you want to make a PR, I'll merge and cut a release.

**Comment by dropofwill** [comment]
Fix has been [released to rubygems](https://rubygems.org/gems/rtasklib/versions/0.2.4)
